services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_LOG_LEVEL: debug
    volumes:
      - mongo_data:/data/db

  springboot-app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    volumes:
      - ~/.config/spring-configs:/config
    depends_on:
      - mongodb

volumes:
  mongo_data: